server:
  port: 8090

logging:
  file:
    name: app.log
    path: /tmp
    max-size: 10MB
    max-history: 7
    clean-history-on-start: true
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS

spring:
  application:
    name: properties-locations

debug: true
