info:
  app:
    name: externalization
    description: externalize the applicaiton properties of a spring project based its profiles
    version: @project.version@

build:
  time: @timestamp@
  #check the @ properties in the pom.xml file